/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainFolder.GUI;

/**
 *
 * @author Ryan Kelly
 */
public class setup extends javax.swing.JPanel {

    /**
     * Creates new form setup
     */
    public setup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Options = new javax.swing.ButtonGroup();
        buttonGroup = new javax.swing.ButtonGroup();
        MinimaxOption = new javax.swing.JCheckBox();
        AlphaBetaOption = new javax.swing.JCheckBox();
        RandomOption = new javax.swing.JCheckBox();
        sliderMinimax = new javax.swing.JSlider();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        sliderAlphaBeta = new javax.swing.JSlider();

        buttonGroup.add(MinimaxOption);
        MinimaxOption.setText("Minimax");
        MinimaxOption.setAutoscrolls(true);

        buttonGroup.add(AlphaBetaOption);
        AlphaBetaOption.setText("Alpha Beta");
        AlphaBetaOption.setAutoscrolls(true);

        buttonGroup.add(RandomOption);
        RandomOption.setText("Random");
        RandomOption.setAutoscrolls(true);

        sliderMinimax.setMajorTickSpacing(1);
        sliderMinimax.setMaximum(6);
        sliderMinimax.setMinimum(1);
        sliderMinimax.setMinorTickSpacing(1);
        sliderMinimax.setPaintLabels(true);
        sliderMinimax.setAutoscrolls(true);

        sliderAlphaBeta.setMajorTickSpacing(1);
        sliderAlphaBeta.setMaximum(8);
        sliderAlphaBeta.setMinimum(1);
        sliderAlphaBeta.setMinorTickSpacing(1);
        sliderAlphaBeta.setPaintLabels(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RandomOption)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MinimaxOption)
                            .addComponent(AlphaBetaOption))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sliderAlphaBeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sliderMinimax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MinimaxOption)
                    .addComponent(sliderMinimax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AlphaBetaOption)
                    .addComponent(sliderAlphaBeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(RandomOption)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox AlphaBetaOption;
    public javax.swing.JCheckBox MinimaxOption;
    private javax.swing.ButtonGroup Options;
    public javax.swing.JCheckBox RandomOption;
    public javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JSlider sliderAlphaBeta;
    public javax.swing.JSlider sliderMinimax;
    // End of variables declaration//GEN-END:variables
}
